dataset: "hyspecnet-11k"
dataset_difficulty: "hard"
bit_depth: 14
sig_num: 6
dropout: 0
N_layers_spatial_lsp: 3
N_layers_spectral_lsp: 3
N_layers_spatial_msp: 2
N_layers_spectral_msp: 2
N_layers_plane: 3
N_layers_params: 2
N_layers_context: 1
dim_msp_spectral: 96
dim_msp_spatial: 96
dim_params: 96
num_mixture: 10
dim_lsp_spatial: 96
dim_lsp_spectral: 96
dim_plane: 96
layerwise_lr: 1
weight_decay: 0
lr_init: 0.0001
device: "cuda"